flyway.url=jdbc:postgresql://ep-fragrant-fire-aph0r6bo-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require
flyway.user=neondb_owner
flyway.password=npg_x9UE8dXOzvsn
flyway.locations=filesystem:src/main/resources/db/migration