-- Add missing columns if they don't exist
ALTER TABLE ars ADD COLUMN IF NOT EXISTS codigo VARCHAR(50) UNIQUE;
ALTER TABLE ars ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;

-- Seed initial ARS data for Dominican Republic
INSERT INTO ars (nombre, codigo, rnc, activo, created_at, updated_at) VALUES
('SENASA - Régimen Contributivo', 'SENASA_CONT', '101010101', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('SENASA - Régimen Subsidiado', 'SENASA_SUBS', '101010102', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Primera ARS de Humano', 'HUMANO', '130000001', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('ARS Mapfre Salud', 'MAPFRE', '130000002', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('ARS Universal', 'UNIVERSAL', '130000003', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('ARS Palic', 'PALIC', '130000004', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('ARS Reservas', 'RESERVAS', '130000005', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('ARS Monumental', 'MONUMENTAL', '130000006', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('ARS Renacer', 'RENACER', '130000007', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('ARS Simag', 'SIMAG', '130000008', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Privado / Sin Seguro', 'PRIVADO', '000000000', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (codigo) DO NOTHING;

